######## General ########
variable "region" {}
variable "aws_profile_name" {}
######## Network ########
variable "cidr" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "database_subnets" {}
variable "azs" {}
variable "ubuntu_22_04_lts_ami" {}
variable "environment" {}
